name: Meteostat Runner
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        station: ["84370","84401", "84501", "84593"]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py for each station
        env:
          STATION_ID: ${{ matrix.station }}
        run: python main.py
        
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-${{ matrix.station }}
          path: data_${{ matrix.station }}.csv
